export const imagePaths = {
  Call_icon: require('../../assets/images/phone_number.png'),
  Location_Icon: require('../../assets/images/Location_1.png'),
  search_icon: require('../../assets/images/search_icon.png'),
  delivery_icon: require('../../assets/images/Layer_1.png'),
  Shopping_Cart_icon: require('../../assets/images/shopping-cart.png'),
  start_icon: require('../../assets/images/fav_sel.png'),
  back_icon: require('../../assets/images/BackArrow.png'),
  Banner: require('../../assets/images/Banner.png'),
  milk_img: require('../../assets/images/milk_img.png'),
  share_icon: require('../../assets/images/share.png'),
  favorite_icon: require('../../assets/images/favorite.png'),
  Illustration_icon: require('../../assets/images/Illustration.png'),
  Home_icon: require('../../assets/images/hom.png'),
  Subscription_icon: require('../../assets/images/sub.png'),
  Order_icon: require('../../assets/images/ord.png'),
  Group_icon: require('../../assets/images/Group.png'),
  Order_check_icon: require('../../assets/images/Order-check.png'),
  Placeholder_Image: require('../../assets/images/place_Holder_01.png'),
  camera_icon: require('../../assets/images/camera.png'),
  photo_library_icon: require('../../assets/images/photo_library.png'),
  Wallet_Icon: require('../../assets/images/wallet.png'),
  Edit_icon: require('../../assets/images/Edit_icon.png'),
  Phone_icon: require('../../assets/images/phone-call_1.png'),
  Info_icon: require('../../assets/images/info_Icon_.png'),
  TICK_ICON: require('../../assets/images/tick.png'),
  CALL_ICON: require('../../assets/images/call.png'),
  CLOSE_ICON: require('../../assets/images/close.png'),
  Replacement_icon: require('../../assets/images/replacement.png'),
  Manage_Products_icon: require('../../assets/images/Manage_Products.png'),
  Make_Payment_icon: require('../../assets/images/Make_Payment.png'),
  Report_Damage: require('../../assets/images/Report_Damage.png'),
  Mark_Vacation_icon: require('../../assets/images/Mark_vacation.png'),
  close_icon: require('../../assets/images/close_icon.png'),
  cancelSubscription: require('../../assets/images/cancel_subscription.png'),
  tick_icon: require('../../assets/images/tick_icon.png'),
  white_tick_icon: require('../../assets/images/white_tick_icon.png'),
  down_arrow_icon: require('../../assets/images/down_arrow.png'),
  ERROR_INFO: require('../../assets/images/error_info.png'),
  Disclosure_Indicator_icon: require('../../assets/images/Disclosure_Indicator.png'),
  information_icon: require('../../assets/images/credit-card.png'),
  logout_icon: require('../../assets/images/log-out.png'),
  my_address_icon: require('../../assets/images/map-pin.png'),
  store_address_icon: require('../../assets/images/map.png'),
  subscription_icon: require('../../assets/images/card_choose_2.png'),
  help_icon: require('../../assets/images/help-circle.png'),
  package_1:require('../../assets/images/package-1.png'),
  logistics_icon: require('../../assets/images/logistics.png'),
  shopping_bag_icon: require('../../assets/images/shopping-bag.png'),
  filter_icon: require('../../assets/images/filter.png'),
  wallet_Icon_1 :require('../../assets/images/wallet_1.png'),
  Whatsapp_icon: require('../../assets/images/whatsapp.png'),  
  Sms_icon: require('../../assets/images/sms.png'),
  Email_icon: require('../../assets/images/mail.png'),
  Notification_icon: require('../../assets/images/notification.png'),
  about_icon: require('../../assets/images/About.png'),
  sorry_icon: require('../../assets/images/sorry.png'),
  CheckBox_icon: require('../../assets/images/check.png'),
  mapSearch_icon: require('../../assets/images/MapLogo.png'),
  Storemap_icon: require('../../assets/images/store-pin.png'),
  clock_icon: require('../../assets/images/clock.png'),
  Person_icon: require('../../assets/images/Person_Icon+01.png'),
  flag_icon: require('../../assets/images/flag.png'),
  promotion_icon: require('../../assets/images/AccountBanner.png'),
  Back_Arrow_icon: require('../../assets/images/BackArrow.png'),
  Explore_icon: require('../../assets/images/Explore-more.png'),
  calender_icon: require('../../assets/images/calendar-icon.png'),
  drop_down_arrow_icon: require('../../assets/images/drop_down_Arrow.png'),
  Recharge_icon: require('../../assets/images/Recharge_banner.png'),
  
  //HelpIcons
  Help_CustomerCare: require('../../assets/images/Help_CustomerCare.png'),
  Help_payment: require('../../assets/images/Help_payment.png'),
  Help_About: require('../../assets/images/Help_About.png'),
  Help_Subscribtion: require('../../assets/images/Help_Subscribtion.png'),
  //flAG 
  Flag_icon: require('../../assets/images/flag.png'),
  
  // Address icons
  briefcase_icon: require('../../assets/images/Help_Subscribtion.png'),
  home_icon: require('../../assets/images/Help_Subscribtion.png'),
  person_icon: require('../../assets/images/Help_Subscribtion.png'),
  location_icon: require('../../assets/images/Help_Subscribtion.png'), 
  arrow_right_icon: require('../../assets/images/right_arrow.png')
};
